# Generated by Django 4.0.5 on 2022-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_time_create_comment_time_update_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to='time_update',
        ),
        migrations.AlterOrderWithRespectTo(
            name='posts',
            order_with_respect_to='time_update',
        ),
    ]
