# Generated by Django 4.0.5 on 2022-07-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_update']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['time_update']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='posts',
            order_with_respect_to=None,
        ),
    ]
