# Generated by Django 4.0.5 on 2022-07-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_rating_ratings'),
        ('books_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('passed_chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapters')),
                ('type_bookmarks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_collections.typebookmarks')),
            ],
        ),
    ]
