# Generated by Django 4.0.5 on 2022-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_rating_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='create_at',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='chapters',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
